### ISSUE TITLE
Support for Redis Sentinel

### ISSUE THREAD

**Issue by vmattila** [nrk/predis#131]
I would be happy to contribute to predis development by implementing automatic master/slave resolution and connection based on the configured sentinels. I tried to explore the Predis codebase, but unfortunately could not figure out where to start.

In practice, we should be able to enter the sentinel addresses instead direct master/slave ip addresses and provide the name of the master. For example:

```php
$sentinels = array(
    'tcp://10.0.0.1:26379/',
    'tcp://10.0.0.2:26379/'
);
$redis = new Predis\Client($sentinels, array('sentinel_master' => 'mymaster');
```

One of the configured sentinels should be connected and sent queries to get the master ip: `SENTINEL get-master-addr-by-name mymaster`, slaves `SENTINEL slaves mymaster` and finally create the actual aggregated connection based on the received information.

Should I create a completely new connection type, extend an existing class or modify something? I also expect that I should implement two new command classes for the two sentinel commands.

Some references:
- http://redis.io/topics/sentinel
- http://redis.io/topics/sentinel-clients

**Comment by ThijsFeryn** [comment]
Any updates, Daniele?

Thx
Thijs

**Comment by integrii** [comment]
Are we sure that you can read/write to any node in the cluster?  The six node cluster I have setup replies with MOVED and the correct node's location.  I then have to connect to that node to complete the write.  Making Predis aware of shards means the process goes faster.  When a MOVED comes back from a server, Predis should ask again for the node distribution.

i could see this being slightly wasteful in small applications that only do one read or write, but long running applications would benefit from it greatly.  Maybe caching the node information should be an option you can enable?

**Comment by ThijsFeryn** [comment]
Hi @nrk & @vmattila 

I considered your advice again (using Sentinel as a strategy rather than a replication connection type). I tried implementing it as a strategy, but it felt wrong.

If you look at the problem Sentinel is trying to solve, it's autofailover and that's directly linked to the replication. Unlike the other strategy patterns, this is initializing new connections.

I believe the implementation of @vmattila is still the right decision.

Would you please consider merging this? I could really use this feature right now. And as mentioned in one of the comments above, Redis Cluster has its own autofailover mechanism. 

Love to hear you opinion and plans for this feature.

Thanks again
Thijs

**Comment by vmattila** [comment]
Just got an email from a user testing my branch. He pointed out a problem with authentication, just copy-pasting the message here so we don't forget the issue:

"I'm testing your feature sentinel for predis.
It works pretty good but did you try redis with AUTH ?
How can you add password to \Predis\Client($sentinel);?

I added $client->auth('mypassword') then it works fine for $client->get() but fails for $client->set()

PHP Fatal error:  Uncaught exception 'Predis\Response\ServerException' with message 'NOAUTH Authentication required.' in /home/labuser/predis-feature-sentinel/src/Client.php:348"

**Comment by nrk** [comment]
@vmattila I guess this is due to the explicit use of `$client->auth()`, the command is sent only to the randomly selected slave but when doing `$client->set()` then the client switches to the master node. The lack of a `password` connection parameter when configuring the connection means that Predis does not have any hint that it must automatically send the `AUTH` command  before the `SET` command to the master node leading to a `-NOAUTH` error.

@ThijsFeryn I'm now convinced that @vmattila's approach is good enough, it probably requires only a few tweaks (`Predis\Connection\Aggregate\SentinelBackedReplication` should reuse the same connection factory instance of the client instead of [creating a new one](https://github.com/vmattila/predis/blob/e49b63754b2bc6437e80cb51b3d1b1cc896c23c9/src/Connection/Aggregate/SentinelBackedReplication.php#L58)) but I think we can ship it in Predis v1.1.

By the way I'm finally (slowly) getting back to actively maintain Predis (and my other OSS projects), sentinel has now the highest priority along with fixes and improvements for redis-cluster support. I'm still browsing the various issues opened in the last few months, but it's just a matter of a few days :-)

**Comment by ThijsFeryn** [comment]
Thanks a lot @nrk, really appreciate it. Keep me posted, OK?

**Comment by danieleteti** [comment]
Any news about sntinel support?

**Comment by nrk** [comment]
@danieleteti I'm working on it, currently tweaking @vmattila's original code and testing some corner cases. If everything goes well I should be ready to push a separate branch onto GitHub this weekend.

**Comment by danieleteti** [comment]
Great! Thank you for your work @nrk

**Comment by matiti** [comment]
Thx for this feature. really nice !

**Comment by melo** [comment]
May I suggest that we use 'service' => 'name_of_sentinel_service' as the way to select to which service you want to connect to? It would be consistent with other clients in other languages...

Without any more parameters, this would connect to the master node of the service.

But if you could also add support for 'role' => 'slave' (see [npm ioredis](https://www.npmjs.com/package/ioredis) for the spec of how it would work - search for "role") that would be very very nice for a project I participate in. We use Sentinel not only for high-availability but also for load-balancing, and a lot of our clients need to connect to a random slave.

Thank you in advance,

**Comment by tom--** [comment]
I hope you can make a success of this feature. Use of Redis at all in our upcoming product depends on having some solution for automated fail-over and recovery that's transparent to the application. I think this might be the last piece of the puzzle.

**Comment by nrk** [comment]
Tomorrow I'll push a `v1.1-sentinel` branch based off the current `master` branch (because yeah support for sentinel will be part of the v1.1.0 release) and picking @vmattila's work as the initial base for sentinel support. The initialization of a client that uses redis sentinel will require the use of the `aggregate` client option instead of `replication` (at least for now), ending up with something along these lines:

```php
$sentinels = [$firstSentinel, $secondSentinel, $thirdSentinel];

$options = [
  'service' => 'name_of_sentinel_service',
  'aggregate' => function () {
    return function ($parameters, $options) {
      $service = $options->service;
      $connectionFactory = $options->connections;

      $replication = new Predis\Connection\Aggregate\SentinelReplication($parameters, $service, $connectionFactory);
    };
  },
]

$client = new Predis\Client($sentinels, $options)
```

In the future with Predis v2.0.0 this will most likely change for the better due to broader changes in the initialization of aggregate connections (cluster, replication), but I guess it will do for now with a few more minor changes before shipping v1.1.0.

@melo I think using `service` makes perfect sense, it also adheres to the same terminology used in the  [guidelines for sentinel-aware clients](http://redis.io/topics/sentinel-clients#redis-service-discovery-via-sentinel). Initially it will be a client option, but it should be possible to put it in the parameters array thus obtaining something like:

```php
$parameters = [
  'service' => 'name_of_sentinel_service',
  $firstSentinel, $secondSentinel, $thirdSentinel,
]
```

As for load-balancing in the context of replication Predis already connects to random slaves for read operations and support for sentinel is implemented on top of that, so I guess we have no use for a `role` option unless I'm missing something or misunderstanding what ioredis does, am I right?

**Comment by nrk** [comment]
As promised we have now a [v1.1-sentinel](https://github.com/nrk/predis/compare/6bc1a38...v1.1-sentinel) branch. Just so that you know I'm completely dissatisfied with the current code needed to initialize the client. Please also note that using the following code:

```php
$sentinels = [$firstSentinel, $secondSentinel, $thirdSentinel];
$service = 'mymaster';

$connection = new Predis\Connection\Aggregate\SentinelReplication($sentinels, $service);
$client = new Predis\Client($connection);
```

... is not an entirely correct approach as both `Predis\Connection\Aggregate\SentinelReplication` and `Predis\Client` should share the same instance of `Predis\Connection\Factory` except for limited and specific reasons. I'm thinking about how to improve this part without shipping some breaking changes which would be incompatible with just a minor version bump.

Aside from that, the first immediate improvement from here will be to refactor out all of the actual code needed to communicate with redis-sentinel to a separate class, `Predis\Replication\SentinelClient` or something along these lines, so that it can be used as a separate and standalone class.

```php
$sentinel = new Predis\Replication\SentinelClient($sentinels, $service);
$connection = new Predis\Connection\Aggregate\SentinelReplication($sentinel);
```

This would remove most of the code from `Predis\Connection\Aggregate\SentinelReplication` and actually we could even avoid exending `Predis\Connection\Aggregate\MasterSlaveReplication` with a new class if it wasn't for the automatic commands retry thing. I can't think of any clean solution to provide the same thing as an option for `Predis\Connection\Aggregate\MasterSlaveReplication` without some messy code.

Thoughts, comments, new ideas and improvements are more than welcome.

**Comment by matiti** [comment]
Yeahhhh ! 

Envoyé de mon iPhone

**Comment by tom--** [comment]
Thanks @nrk. We'll be trying it out in due course.

**Comment by nrk** [comment]
Thanks @tom-- that would be a great help, I hope to get feedback from everyone interested in this, and ideas on how it can be improved before shipping a new minor release (I think it won't happen at least until the end of September, I also have to add some missing stuff to the redis-cluster part).

**Comment by PunKeel** [comment]
Thanks a lot for working on this !

**Comment by nrk** [comment]
Still no feedback? :crying_cat_face: I've started refactoring parts of code in this branch but I still can't find a proper way to avoid extending `Predis\Connection\Aggregate\MasterSlaveReplication` which is kind of my pet peeve. The next step is having unit tests...

**Comment by ThijsFeryn** [comment]
@nrk I tested the branch and like the code the way it is. I don't mind having a class that extends MasterSlaveReplication.

Unit tests would be nice, once you reach stable code, I wouldn't mind assisting with the tests.

**Comment by vmattila** [comment]
I agree with @ThijsFeryn that extending `MasterSlaveReplication` would not be that bad. Somehow I feel that building it other way could lead to unnecessary code duplication, maybe?

I'm also happy to help with the tests.

**Comment by ecolinet** [comment]
Hi @nrk, we have a use case where we need to use redis behind sentinel. 

But we are stuck with redis authentication. Any way to make it work ?

Here is the code used :
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$options = array(
    'service' => 'master-name',
    'database' => 'database',
    'prefix' => "myprefix_"
);

$options += [
    'aggregate' => function () {
        return function ($sentinels, $options) {
            return new \Predis\Connection\Aggregate\SentinelReplication($sentinels, $options->service, $options->connections);
        };
    },
];

$sentinels = [
    'tcp://localhost:26379'
];

$client = new Predis\Client($sentinels, $options);
$client->auth('mypassword'); // AUTH 

try {
    $client->set('test', 123);
    echo $client->get('test');
    $client->del('test');
} catch (\Exception $e) {
    echo get_class($e), ': ', $e->getMessage(), "\n";
}
```

With authentication enabled :

    Predis\Response\ServerException: NOAUTH Authentication required.

In fact it seems that the Predis\Client::auth method is not really sent.

Thanks for your feedback on this.

**Comment by ecolinet** [comment]
Found !

```php
$options += [
    'aggregate' => function () {
        return function ($sentinels, $options) {
            /* @var $connectionFactory \Predis\Connection\Factory */
            $connectionFactory = $options->connections;
            $connectionFactory->setDefaultParameters(array(
                'password' => $options->password
            ));

            $sentinelReplication = new \Predis\Connection\Aggregate\SentinelReplication($sentinels, $options->service, $connectionFactory);
            $sentinelReplication->setAutomaticRetry(false);

            return $sentinelReplication;
        };
    },
];
```

**Comment by crispygoth** [comment]
Just to add a quick "me too" to this thread -- I've just started using this branch to connect to a Redis instance that's using Sentinel, and so far everything is working fine in my development environment. It'll be a couple of months before this hits a production system, and there should be some proper stress-testing before then. I'll let you know if we come across any issues!

**Comment by melo** [comment]
@nrk sorry, just noticed your comment.

Our use for sentinel support and the role parameter is to be able to use the master when we need to write, or to use a random slave when we just need to read (and in this case we can load-balance between multiple slaves).

That was the intent of role, but if we can get it any other way, I'm happy.

We need this to use with Magento code base.

**Comment by winfan** [comment]
$ php replication_sentinel.php
PHP Fatal error:  Cannot use object of type Predis\Response\Error as array in /Library/WebServer/Documents/predis-1.1-sentinel/src/Connection/Aggregate/SentinelReplication.php on line 207

why?

**Comment by nrk** [comment]
@winfan I'm pretty sure it's the same issue described in #289. I'm going to have a whole week off from work at the start of the new year and I'm planning to use part of that time to push some pending fixes and hopefully release this long-awaited new version with support for redis-sentinel.

**Comment by winfan** [comment]
@nrk sorry! I just saw
$ php replication_sentinel.php                                                                     
PHP Fatal error:  Uncaught exception 'Predis\Response\ServerException' with message 'MOVED 12182 127.0.0.1:6382' in /Library/WebServer/Documents/predis-1.1-sentinel/src/Client.php:365
Stack trace:
#0 /Library/WebServer/Documents/predis-1.1-sentinel/src/Client.php(330): Predis\Client->onErrorResponse(Object(Predis\Command\KeyExists), Object(Predis\Response\Error))
#1 /Library/WebServer/Documents/predis-1.1-sentinel/src/Client.php(310): Predis\Client->executeCommand(Object(Predis\Command\KeyExists))
#2 /Library/WebServer/Documents/predis-1.1-sentinel/examples/replication_sentinel.php(40): Predis\Client->__call('exists', Array)
#3 /Library/WebServer/Documents/predis-1.1-sentinel/examples/replication_sentinel.php(40): Predis\Client->exists('foo')
#4 {main}
  thrown in /Library/WebServer/Documents/predis-1.1-sentinel/src/Client.php on line 365

redis cluster how to work

**Comment by nrk** [comment]
@winfan redis cluster has nothing to do with sentinel so you cannot use that example anyway. Just have a look at [this paragraph in the README](https://github.com/nrk/predis#cluster), the client will do the rest.

**Comment by dinnyosz** [comment]
Thx @nrk for your work, do you have any news about when this feature will hit the stable branch?

**Comment by ziv-k** [comment]
@nrk, finalizing this feature would be wonderful.

**Comment by vmattila** [comment]
I have used the current v1.1-sentinel branch in multiple production environments without real problems.

100 ms default timeout has been slightly too low in our environment (for some reason) when sentinels have been distributed around different AWS availability zones. This is just to give heads up that most likely the timeout needs to be adjusted for each implementation for best performance.

Do you think that sentinels should actually be connected in random order? As now they are connected in the same order as they are defined, there will be kind of "unnecessary" and constant delay if first sentinels are down. Of course we could implement a completely new component to provide the sentinels in any order, just thinking whether it should be part of Predis or not.

**Comment by nrk** [comment]
I'm currently travelling around Taiwan so I'm basically afk for a while,
I'll be addressing this feature once and for all (along with a much needed
new release of Predis) around mid-April when I'm back home :-)
Il 27/mar/2016 21:07, "Ville Mattila" <notifications@github.com> ha scritto:

**Comment by nrk** [comment]
Alright I'm not dead. I resumed my work on Predis and am planning to tinker on the `v1.1-sentinel` branch this week and merge it into the `master` the next weekend, please note that I will most likely push a few minor breaking changes in `Predis\Connection\Aggregate\SentinelReplication` in the process. After that I'll be working on various fixes (especially for redis-cluster) before releasing `v1.1.0` hopefully in a month but in the meanwhile I hope devs will be able to test the changes in redis-sentinel and report issues or missing features before shipping the new release. Thanks!

**Comment by nrk** [comment]
@vmattila I think connecting to a random sentinel makes also sense to distribute the load among the various sentinels provided via configuration, I will probably make it the default behaviour in Predis.

**Comment by tback** [comment]
Nice to hear this is moving forward. Please consider #291 (database selection) as well. I implemented a redneck version of this in https://github.com/traum-ferienwohnungen/predis/commit/5887201aa5f0c73070917aded44b4eef95355cee

**Comment by nrk** [comment]
@tback don't worry it's on the roadmap, well actually I think I'll just do something on the same line of [`Predis\Connection\Aggregate\RedisCluster::setDefaultParameters()`](https://github.com/nrk/predis/blob/v1.0.3/src/Connection/Aggregate/RedisCluster.php#L536-L552) so that you can actually specify more than just `database`.

**Comment by nrk** [comment]
First step in the right direction: forget the scary block of code previously needed to configure `Predis\Client` to use redis-sentinel, now you can just do the following:

```php
$sentinels = ['tcp://127.0.0.1:5380', 'tcp://127.0.0.1:5381', 'tcp://127.0.0.1:5382'];
$options = ['replication' => 'sentinel', 'service' => 'mymaster'];

$client = new Predis\Client($sentinels, $options);
```

You can still use the `aggregate` option passing a callable if you need more control over the initialization of the underlying connection.

**Comment by nrk** [comment]
Just added support for [`ROLE`](http://redis.io/commands/role) in f8b3f18 which was an important missing bit for proper support of redis-sentinel (see http://redis.io/topics/sentinel-clients). Please note that the `ROLE` command was added in Redis 2.8.12 so Predis won't work with older versions of Redis 2.8. Prior to the introduction of `ROLE` clients had to rely on the output of `INFO` (definitely suboptimal) and I'm thinking about skipping that and just live with a minimum required version of Redis.

**Comment by nrk** [comment]
In the end I'm rewriting the whole `Predis\Connection\Aggregate\SentinelReplication` class from scratch without extending `Predis\Connection\Aggregate\MasterSlaveReplication` in order to squeeze a few more optimizations (e.g. Predis won't ask either for the master or the list of slaves unless necessary, thus avoiding a useless round-trip). All in all I'd say it's turning out really well and I'm pretty much satisfied with the result!

My plan is to merge the `v1.1-sentinel` into `master` as-is so that more people can start "playing" ASAP with redis-sentinel and create a new branch `v1.1-sentinel-rewrite` (or something like that) for the braves that will be kind enough to do some early testing with the new approach. The next and last step will be writing tests for the test suite...

**Comment by nrk** [comment]
@tback database selection and authentication will both be possible by setting `database` and `password` in an array passed to the `parameters` client option. This is an example of configuration that will use the same database and password for every connection when using redis-sentinel:

```php
$sentinels = ['tcp://127.0.0.1:5380', 'tcp://127.0.0.1:5381'];

$options = [
    'replication' => 'sentinel',
    'service'     => 'mymaster',
    'parameters'  => ['database' => 2, 'password' => 'MYPASSWORD'],
];

$client = new Predis\Client($sentinels, $options);
```

**Comment by nrk** [comment]
I updated `v1.1-sentinel` with the rewritten `Predis\Connection\Aggregate\SentinelReplication` class (see b047e8b for the diff) which means now I need your feedback. If you want to see what happens under the hood using a CLI script you can use this quick&dirty connection class:

```php
class DebugConnection extends StreamConnection
{
    public function connect()
    {
        if (!$this->isConnected()) {
            echo "[$this] ** CONNECTING\n";
            parent::connect();
        }
    }

    public function disconnect()
    {
        if ($this->isConnected()) {
            parent::disconnect();
            echo "[$this] ** DISCONNECTED\n";
        }
    }

    public function executeCommand(CommandInterface $command)
    {
        $response = parent::executeCommand($command);
        echo "[$this] => ", $command->getId(), " ", join(" ", $command->getArguments()), "\n";

        return $response;
    }
}
```

Then initialize the client like this:

```php
$client = new Predis\Client($sentinels, [
    'replication' => 'sentinel',
    'service' => $yourservice,
    'connections' => ['tcp' => 'DebugConnection'],
]);
```

**Comment by lulyon** [comment]
That's Great!  I would be very glad to follow the new approach for configuring Predis\Client to use redis-sentinel, and test the frequently used redis io features.

**Comment by nrk** [comment]
Now we also have tests for [`Predis\Connection\Aggregate\SentinelReplication`](https://github.com/nrk/predis/blob/v1.1-sentinel/src/Connection/Aggregate/SentinelReplication.php)  (commit d6d30769), they are already a good bunch but I'll add a few more in the next days. I think the `v1.1-sentinel` branch is basically almost ready to get merged into `master`, I'd love to hear some feedback just in case anyone had the chance to give it a spin already in the last 5-6 days. Thanks!

PS: Predis v1.1.0 is planned to be release during the first week of June, we're almost there :)

**Comment by nrk** [comment]
I went ahead and merged `v1.1-sentinel` into `master` because I think everything looks good, consequently I'm closing this issue. If you encounter any problem with this new redis-sentinel connection class please open a new specific issue instead of posting new comments on this one. Thanks for the long wait, I admit it took quite a while :smile:

**Comment by tom--** [comment]
thanks @nrk

**Comment by ThijsFeryn** [comment]
Thanks @nrk. Any idea when the new release will be planned? Rather use a new release than dev-master in my composer.json.

Cheers
Thijs

**Comment by nrk** [comment]
@ThijsFeryn very soon, I'd say during the he first week of June.

**Comment by nrk** [comment]
JFYI Predis v1.1.0 is now available so we finally have redis-sentinel support in a stable release! Please read the [release notes](https://github.com/nrk/predis/releases/tag/v1.1.0), it took quite some time (and in case of redis-sentinel, way too much time) but thanks for waiting!

**Comment by seoilkyu** [comment]
good! all clear thanks

**Comment by andrewmclagan** [comment]
Thank you!!!
