### ISSUE TITLE
Question about expireat command

### ISSUE THREAD

**Issue by jarodium** [nrk/predis#224]
Hello there i'm trying to expire a key till the end of this year.
```
$x = $redis->exists($K);					
$redis->lpush($K,$data);
if (!$x) 
{
    $t = mktime(0,0,0,12,31,date("Y"));
    $redis->expireAt($K,$t);
}
```
When I inspect the TTL with phpRedisAdmin, I get the following value 3630304 .
With phpRedisAdmin I can set a proper TTL.

The $redis->expireAt command returns true but the value is wrong.

Am I missing something?
Regards

**Comment by nrk** [comment]
@jarodium why should it be considered a wrong value? Supposing that you executed that snippet the same day you opened this issue, a TTL of 3630304 seconds (42 days) was indeed the amount of time left to the year end so I'd say it's correct.

**Comment by jarodium** [comment]
@nrk Thank you for taking the time reviewing this.
Here is a more compreensive test:
```
$K = "test";
//este é o hash gerado para o cliente define('UNIQ',hash('sha1',$_SERVER['HTTP_HOST']));
$x = $redis->exists($K);                    
$redis->lpush($K,$data);
if (!$x) 
{
    $t = mktime(0,0,0,12,31,date("Y"));
    $redis->expireAt($K,$t);
    
    echo $t; // returns 1451520000
}
else {
	echo "--- ".$redis->ttl($K); //returns 31276701 should be correct according to Redis.
}
```
Below a screenshot of the key at php redis admin.
![screenshot_section](https://cloud.githubusercontent.com/assets/1470446/5600806/779bdd24-92db-11e4-8d6c-d8e46b952d4a.png)

Don't quite understand why mktime would yield a value different or at least, not creating a figure somewhere in the 3127**** if ExpiresAt accepts a Unix Timestamp....

**Comment by TomAdam** [comment]
You are asking Redis for TTL (time to live). It wouldn't make sense if it returned the time the key was to expire rather then the number of seconds left to expiry. When you use ```EXPIREAT``` Redis internally calculates the number of seconds between now and the time you want to expire at and stores that value instead. Put in other terms, it is storing delta time rather than absolute. Subsequent calls to ```TTL``` should give a lower number as the time runs out, with it hitting 0 at the time you set with ```EXPIREAT```.

**Comment by nrk** [comment]
There's no issue, see @TomAdam's clear explanation about how `EXPIREAT` and `TTL` work.
