### ISSUE TITLE
Memory bloating in pipeline

### ISSUE THREAD

**Issue by opb** [nrk/predis#234]
Hi there

I'm taking an 850,000 line CSV file and json encoding and adding each row to redis. Here is the function that is run on each row:

```php
protected function processRow($row, $count)
{
	$this->pipe->lpush('csv-queue', json_encode($row));
	$count++;
	if($count % 200 == 0)
	{
		$this->pipe->execute();
		echo '.';
	}
	if($count % 10000 == 0)
	{
		echo PHP_EOL.number_format((memory_get_usage(true) / 1000000), 2).PHP_EOL;
	}

	return $count;
}
```
As you can see, I'm executing the pipeline every 200 rows, and printing a dot, and then every 10,000 rows I'm printing memory usage. I get the following output:

```
2015-01-09T16:56:53+00:00 Processing /home/vagrant/BasicCompanyData-2015-01-01-part1_5.csv
..................................................
17.30
..................................................
19.92
..................................................
22.28
..................................................
24.90
..................................................
27.00
..................................................
29.36
..................................................
32.24
..................................................
34.60
..................................................
36.96
..................................................
39.32
..................................................
41.68
```
... and so on.

I made a change to re-instantiate the pipeline every 10,000 rows as well:

```php
if($count % 10000 == 0)
{
	echo PHP_EOL.number_format((memory_get_usage(true) / 1000000), 2).PHP_EOL;
	$this->pipe = $this->cache->pipeline();
}
```
This then gives the following:
```
2015-01-09T17:46:06+00:00 Processing /home/vagrant/BasicCompanyData-2015-01-01-part1_5.csv
..................................................
17.30
..................................................
17.30
..................................................
17.30
..................................................
17.30
..................................................
17.30
..................................................
17.30
..................................................
17.30
```
So recreating the pipeline object prevents memory usage from bloating. Is this expected behaviour?

Many thanks!

**Comment by nrk** [comment]
This is an expected behavior. When using a pipeline commands with their arguments are enqueued and thus stay in memory as objects until the `execute()` method is invoked, then all of the queued commands are written to Redis in one go and responses from the server are read in bulk after that.

Instead of creating a new pipeline object every time (if you don't invoke `execute()`, all of the queued commands are discarded!) you should do ```$pipe->flushPipeline()```: this will empty the buffer writing everything to Redis, but beware that the responses returned from the server will still be read and stored in memory adding up to the memory usage.

At this point, if you don't care about the responses returned by Redis you can simply ignore them by creating your pipeline using the _fire-and-forget_ option:

```php
$pipe = $client->pipeline(['fire-and-forget' => true]);
```

**Comment by opb** [comment]
Thanks, adding in `fire-and-forget` fixed the issue!
