### ISSUE TITLE
Predis\Connection\StreamConnection::tcpStreamInitializer taking a very long time

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [nrk/predis#247]
Is there a faster alternative in the title? it seems to be causing huge amounts of overhead which I assume is due to opening/closing connections possibly on every transaction. My first thought is keeping a connection alive for the duration of the entire transaction however I had thought this was already set with the way Predis is configured.

Any insight on this would be great!

Also using Redis cluster with 6 master nodes

**Comment by markomafs** [comment]
I have the same problem, but i'm using a cluster with 2 nodes.

**Comment by nrk** [comment]
Connections are kept alive until the client instance is garbage collected (generally at the end of the lifetime of a request) or they are explicitly closed, but they are not persistent between requests (unless you specify the `persistent` connection parameter).

Have you noticed what actually makes `tcpStreamInitializer()` slow? If most of the time is spent by PHP's `stream_socket_client()` then there's not much we can do about this.

**Comment by Ewan-GrandSlam** [comment]
I believe I've located the underlying issue, which was with the timeout on redis itself. Apparently set to 0 you will create a new connection for each instruction you send. Setting the timeout to 300 via redis-cluster config seemed to resolve the issue.

The only other thing left to figure out is a few "read error on line" issues which I presume has something to do with the read_write_timeout.

**Comment by nrk** [comment]
@Ewan-GrandSlam I'm not sure it's related to that because having `timeout` set to `0` in `redis.conf` actually disables timeouts so that idle connections are not closed, while a value of `300` means that idle connections are closed after 300 seconds.

On the other hand, an excessively small value for `read_write_timeout` when configuring the client can indeed lead to errors while reading back responses from Redis.

**Comment by Don87** [comment]
Profiling my web app home page shows it takes 2.06 seconds to load, over 50% of that (1.04s) is spent on fgets called by Predis\Connection\StreamConnection. I am not a super pro at this or anything, but if and when I get the real issue of this I shall post back here.

**Comment by Don87** [comment]
Ok this is getting a bit strange, apparently, of the aforementioned load time a further 459ms is spent on fread called by Predis\Connection\StreamConnection and another 235ms spent on called by Predis\Connection\StreamConnection::tcpStreamInitializer

**Comment by nrk** [comment]
@Don87 where is the redis instance your app is connecting to? localhost, local network or some remote host?

**Comment by Don87** [comment]
@nrk You are right, I had 11 geo-distributed web servers so for data consistency I decided they share 1 remote redis server. I tested with a local redis server and voila, times reduced greatly. I googled about and settled for localhost slaves for reads with a remote master for writes. Sorry for my naivety.
Regards.

**Comment by nrk** [comment]
@Don87 don't worry, I'm glad you were able to come up with a solution that suits your needs!

**Comment by Don87** [comment]
@nrk Thanks and I am very grateful for Redis library - it's awesome!
Cheers.

**Comment by baselbj** [comment]
as I understand the using redis as remote host may cause performance issues? as we are developing an application that needs a shared remote host redis to share common data.

unfortunately it seems the connection is closed each time we perform a send or get request. I tried changing the connection configuration making time out to 0 and connection to persistent but I had the same slow performance while sending multiple get or set. my configuration is:

 array(
        'scheme' => 'tcp',
        'host' => 'my host ip',
        'port' => '6379',
        'persistent' => TRUE,
        'timeout ' => 0,
        ),

**Comment by The-Don-Himself** [comment]
For me this issue was almost 3 years ago, 2015. I've gained a ton load of experience since then, off the top of my head, slow performance can be mainly attributed to :- 
1.) The latency (distance) between the Redis instance(s) and your server.
2.) The amount of data being persisted, fetched at any on point in time and how (multige/single)

This assumes the network bandwidth is not an issue or other factors. I've also experienced serious performance issues and timeouts with shared redis instances like Azure shared redis, which is expected as explained in their TOS but experiencing it frequently is always a shocker, try upgrade to basic or premium in that case.

All in all, the only way you can be properly helped is by profiling your setup perhaps using something like blackfire and see exactly where the issues lie.

All the best.

**Comment by baselbj** [comment]
Thank you :)
