### ISSUE TITLE
`__invoke` support on Options causes autoloading of non-existent class

### ISSUE THREAD

**Issue by dominics** [nrk/predis#257]
In the ~1.0 `Predis\Configuration\Options`, we support `__invoke` like this:

```php
if (method_exists($value, '__invoke')) {
    $value = $value($this, $option);
}
```

But we don't check whether `$value` is an object. Unfortunately, `method_exists` can operate on string class names, and will cause autoloading. That means, using simple client options like `['cluster' => 'predis']` will cause an autoloading attempt for a class named `\predis`.

Sure, autoloading should fail, and `method_exists` should return `false`. But the autoloading should be avoided in the first place. (`method_exists` doesn't have an `$autoload = false` param like `class_exists` does.)

The simplest solution is to check for an object before looking for the `__invoke` method.

This is particularly a problem for my use of Predis, because the project I'm working on has a deep autoloader stack (ordered by likelihood of success), and a missed autoload is quite expensive. (A couple of seconds! Yeah, crazy, I know.)

**Comment by dominics** [comment]
Here's a quick example:

```php
class foo {
    public function __invoke()
    {
        echo 'bar';
    }
}

$client = new Predis\Client(['tcp://127.0.0.1', 'tcp://127.0.1.1'], ['cluster' => 'foo']);
```

This code gives "PHP Fatal error:  Call to undefined function foo() in <root>/vendor/predis/predis/src/Configuration/Options.php on line 104" instead of an exception.

**Comment by nrk** [comment]
This is a scenario I had not considered, your fix makes sense as we don't actually care if a class implements `__invoke` but we just need to know that the passed _instance_ responds to `__invoke`. Also, in light of your additional comment, I consider this one a bug.

Will merge #258 in the next few days, for now I'm just catching up with the other issues and PRs due to my half-year absence from the OSS scene :-)

Thanks!
