### ISSUE TITLE
When subscribe I can't use other commands ?

### ISSUE THREAD

**Issue by iyaozhen** [nrk/predis#274]
I use examples/pubsub_consumer.php like this:
```php
Predis\Autoloader::register();
$redis = new Predis\Client([
    'scheme' => 'unix',
    'path' => $sysConfig['redis_sock'],
    'persistent' => true,
]);

// Initialize a new pubsub consumer.
$pubsub = $redis->pubSubLoop();
// Subscribe to your channels
$pubsub->subscribe('im_platform_log', 'control_channel');

$redis2 = new Predis\Client([
    'scheme' => 'unix',
    'path' => $sysConfig['redis_sock'],
    'persistent' => true,
]);
$expireTime = 60 * 10;
……
case 'message':
            if ($message->channel == 'control_channel') {
                if ($message->payload == 'quit_loop') {
                    echo 'Aborting pubsub loop...'.PHP_EOL;
                    $pubsub->unsubscribe();
                }
                else {
                    echo "Received an unrecognized command: {$message->payload}.".PHP_EOL;
                }
            }
            else {
                $logStr = $message->payload;
                ……
                if (!$redis2->exists($callKey)) {
                    $redis2->hmset($callKey, [
                        'success' => 0,
                        'failure' => 0,
                    ]);
                    $redis2->expireat($callKey, $reqtimeUnix + $expireTime);
                }
            }
……
```
As you see,  I hope subscribe data then counter for some data;
But:
![image](https://cloud.githubusercontent.com/assets/4395553/9382514/1dae9a10-4774-11e5-80de-c153cef6a1a2.png)

This is my first use redis, I am very confusing.

**Comment by nrk** [comment]
If you use the same unix domain socket as a persistent resource (see `persistent => true`) for both clients then you are actually reusing the same underlying socket resource. In this case if `$redis` enters a PUBLISH/SUBSCRIBE context the same happens for `$redis2` because Redis itself marks the very same connection in that particular state. Using PHP's persistent connections with Redis may introduce weird behaviours especially when using UNIX domain sockets so they should be used carefully or even avoided when not strictly necessary.

**Comment by iyaozhen** [comment]
Aha! Thank you very much.

So it seems that, PHP use persistent connect must be carefully and more test. 
In this case, redis is same as mysql. When connecting, the function would first try to find a (persistent) link that's already open with the same host(unix socket).

In fact, I not necessary use persistent link.
