### ISSUE TITLE
Redis connection pool using Predis

### ISSUE THREAD

**Issue by akshaygupta1989** [nrk/predis#276]
I am using Predis in my application. And it has worked wonderfully well for us till now. As we are scaling, I am looking to implement connection pool using on top of this library. 

Are there any implementations already available? Basic search didn't lead me to anyone.

**Comment by nrk** [comment]
There's no way of implementing a connection pool in PHP (especially when relying on userland code alone) due to the very nature of PHP and that's why you won't find anything like that. The most you can do is using persistent connections but it's not the same thing, and they must used carefully to avoid possible problems with the state of the connection (e.g. reusing a connection when `MULTI` has not been properly finalized with `EXEC` or `DISCARD`).

**Comment by spiritix** [comment]
@nrk could you please further elaborate why there is no way to implement that in PHP? From my POV this should be feasible, one configures a pool limit somewhere and then Predis opens a new connection (or reuses an existing connection from the pool) for every operation until the limit is reached.

**Comment by nrk** [comment]
@spiritix that would require some kind of support by the PHP engine in order to have the ability to store and keep track of open connections between requests, but PHP does not offer anything like that.

**Comment by spiritix** [comment]
IMHO, this could be solved by using persistent connections. And then use PHP to manage the distribution of commands within the open connections. Will try to implement a quick prototype and see if it works.

**Comment by nrk** [comment]
@spiritix honestly I'm not sure it's feasible but if you manage to make it work then contributions are more than welcome :+1:

**Comment by spiritix** [comment]
Just did a quick test. The problem is if I don't use persistent connections, all connections need to be initialized again at the beginning of every request, which is obviously not feasible. If I use persistent connections, Predis seems to not create new connections but instead use only one connection, even though I am explicitly creating new instances. Shouldn't persistence just re-use connections over multiple requests and not merge connections within one request?

**Comment by namjithwisilica** [comment]
Is there any way to set max or dedicated persistent connection count?

**Comment by odahcam** [comment]
Disclaimer: afaik Predis is a blocking library. For anyone coming here not yet having implemented Redis communication and expecting a non-blocking Redis client I suggest https://github.com/amphp/redis. For anyone already using Predis you can hack it to use Amp's connection under the hood.
