### ISSUE TITLE
Missing payload type check

### ISSUE THREAD

**Issue by djagya** [nrk/predis#289]
https://github.com/nrk/predis/blob/v1.1-sentinel/src/Connection/Aggregate/SentinelReplication.php#L206

Here `$payload` could be a `Predis\Response\Error` object with message e.g. `IDONTKNOW I have not enough information to reply. Please ask another Sentinel.`.

So working with payload as an array in return will throw a fatal error `Cannot use object of type Predis\Response\Error as array`. Shouldn't be `$payload` be checked whether it's an Error class object and throw `ConnectionException` (to reevaluate goto block in querySentinel)?

Like this for example:
```php
protected function getMasterFromSentinel(NodeConnectionInterface $sentinel, $service) {
....
    if ($payload instanceof Error) {
        throw new ConnectionException($sentinel, $payload->getMessage());
    }

    return array(
        'host' => $payload[0],
        'port' => $payload[1],
        'alias' => 'master',
    );
}
```

**Comment by nrk** [comment]
Thanks, fixed in be8ac3e2057af02d6c4f1137a491039d29f75b76 but please note that the error response `-IDONTKNOW` has been removed since long ago as it was part of the oldest implementation of redis-sentinel. Actually the only error that `SENTINEL GET-MASTER-ADDR-BY-NAME` can return right now is `-ERR No such master with that name` which is also OK to have it propagated to the caller (although we should probably throw a different exception for such error).
