### ISSUE TITLE
Support for failover？

### ISSUE THREAD

**Issue by cynial** [nrk/predis#314]
I'm using cluster mode currently, I have 3 master nodes and 3 slave nodes, and the config is:

`$parameters = ['tcp://10.0.0.1', 'tcp://10.0.0.2','tcp://10.0.0.3','tcp://10.0.0.4','tcp://10.0.0.5','tcp://10.0.0.6'];`
`$options    = ['cluster' => 'redis'];`
`$client = new Predis\Client($parameters, $options);`

Then I kill the `10.0.0.1`, I get the ConnectionException: `Connection refused [tcp://10.0.0.1`], but actually the redis cluster is still working fine.

Does predis not support failover?

**Comment by mstaack** [comment]
@nrk whats the status here?

**Comment by mstaack** [comment]
okay got it https://github.com/nrk/predis/issues/318

**Comment by nrk** [comment]
Starting with v1.0.4, when the execution of a command results in a connection error the client removes the failed connection from the pool and connects to a random node of the cluste in order to fetch the new slots map via `CLUSTER SLOTS` and perform a new attempt to execute that command using the new cluster configuration.
