### ISSUE TITLE
Why FOR in writeRequest()?

### ISSUE THREAD

**Issue by dmitry-php** [nrk/predis#316]
Hi @nrk and all!
Could you please explain why you use FOR in StreamConnection::writeRequest() ?

I have an exception in case of passing assoc array (or array like [0 => 'someKey', 2 => 'someKey'] - thinks this is same) to $redis->del([someAssocArray]);

https://github.com/nrk/predis/blob/v1.0/src/Connection/StreamConnection.php#L284-L288

If we can change FOR to FOREACH in StreamConnection::writeRequest() I thinks this can prevent exception firing.

**Comment by Danack** [comment]
Please post a code example of something not working if you think something is broken.

**Comment by nrk** [comment]
@dmitry-php the reason for using a `for` loop instead of a `foreach` loop is mostly for the sake of some good (or bad? :)) micro-optimizations (`foreach` uses more memory and has more overhead than `for`) that I welcome in Predis in a few selected areas. Although I understand your point, you should really make sure that you are not passing associative arrays to Predis methods that map to variadic Redis commands. Maybe you can just use `array_values()` when you fear having some corner-cases such as `[0 => 'someKey', 2 => 'someKey']`.

**Comment by dmitry-php** [comment]
@nrk I guess this was micro-optimisation:) But don't you think that this optmization would be miserable if users always need to execute array_values()... or maybe sort() before passing array to some Predis method?

I think all of this need some profiling and looking to results.

Thanks for your response @nrk :)

**Comment by nrk** [comment]
Fixed :smile: Connection classes based on phpiredis serialized commands with holes in their arguments just fine so it didn't make any sense to have a different behaviour for `Predis\Connection\StreamConnection` and the use of `for` wasn't even worth as a micro-optimization in this context after some tests. Thanks!
