### ISSUE TITLE
Fatal when using KeySpace iterator

### ISSUE THREAD

**Issue by iUtvikler** [nrk/predis#327]
_Predis 1.0.3
Redis 2.8.23
PHP 5.3.29
Ubuntu 14.04.4_

I get a fatal error when using the KeySpace iterator. 
`Fatal Error (E_ERROR): Cannot use object of type Predis\Response\Status as array`

[CursorBasedIterator::executeCommand](https://github.com/nrk/predis/blob/v1.0/src/Collection/Iterator/CursorBasedIterator.php#L120) returns Predis\Response\Status instead of an array..

A var export of the response yields `Predis\Response\Status::__set_state(array( 'payload' => 'QUEUED', ))`.

I'm connecting to AWS Elasticcache and here is my code:

```PHP
foreach (new \Predis\Collection\Iterator\Keyspace($client, $keyPrefix.$pattern) as $key) {
    $tx->del(substr($key, strlen($keyPrefix)));
}
```

**Comment by nrk** [comment]
`+QUEUED` responses are returned only inside a [transaction context](http://redis.io/topics/transactions) (commands issued after a `MULTI` command and before `EXEC` or `DISCARD`), on the other hand cursor-based iterators cannot work inside a transaction (this limit is not due to che client but how Redis works). Can you double check the rest of your code? It would also help to have the whole stack trace of the exception.

**Comment by iUtvikler** [comment]
Ahh thanks I am running inside a transaction. 
I did not have issues with this code when running against Redis 3.0.t btw..

```PHP
try {
    $client->transaction(function($tx) use ($client, &$count, $filename, $pattern) {
        $keyPrefix = $client->getOptions()->prefix;

        foreach (new \Predis\Collection\Iterator\Keyspace($client, $keyPrefix.$pattern) as $key) {
            $tx->del(substr($key, strlen($keyPrefix)));
            $count++;
        }
    });
} catch (\Predis\Transaction\AbortedMultiExecException $e) {
    return false;
}
```

So should i just map the keys from the iterator to an array outside of the transaction?

Thanks for the quick response!

**Comment by nrk** [comment]
Redis 3.0 shouldn't make any difference in this respect so you should still see an exception being thrown, but anyway yes you can get the keys outside of the transaction and process them later (you can use [`iterator_to_array()`](http://php.net/manual/en/function.iterator-to-array.php) to easily obtain an array out of `Predis\Collection\Iterator\Keyspace`).

**Comment by iUtvikler** [comment]
great thanks!

**Comment by iUtvikler** [comment]
Actually I had to specify the prefix. The iterator iterates all the keys if i dont..
Do you want me to file an issue for that?

redis-cli: `SET should_not_iterate me`

```PHP
require 'vendor/autoload.php';

$client = new Predis\Client(array(
  'host' => '46.101.143.91',
  'password' => 'nZLEX2WWm7YZwC'
), array('prefix' => 'my_prefix'));

$keys = iterator_to_array(new \Predis\Collection\Iterator\Keyspace($client, '*'));

var_dump($keys);

/*
array(5) {
  [0]=> string(17) "shoul_not_iterate"
}
*/
```

**Comment by nrk** [comment]
@iUtvikler no sorry, I was wrong! :-) Predis doesn't automatically apply the prefix when issuing the underlying `SCAN` command used to iterate the keyspace and that's actually the intended behaviour, at least for now. The problem here is that the keys returned by `SCAN` in the response payload always contain the prefix for obvious reasons, so being explicit is probably the best way to avoid confusion... or at least that was my reasoning at the time of implementing this feature.
