### ISSUE TITLE
Support for Redis Geo?

### ISSUE THREAD

**Issue by Horki** [nrk/predis#336]
- I see there are missing command for http://redis.io/commands#geo

**Comment by nrk** [comment]
Yeah I am working on it right now, that's actually what is delaying v1.0.4 (it's actually pretty quick to add new commands in Predis, it just take a while to also have tests for them in the repository).

**Comment by nrk** [comment]
BTW [`BITFIELD`](http://redis.io/commands/BITFIELD) is missing too right now.

**Comment by nrk** [comment]
The following commands added in Redis 3.2 will be available starting with Predis v1.0.4: `GEOADD`, `GEOHASH`, `GEOPOS`, `GEODIST`, `GEORADIUS`, `GEORADIUSBYMEMBER` along with `HSTRLEN` (already implemented a while ago)  and `BITFIELD`. Since Predis v1.0.x will stick with `3.0` as the default server profile, you must initialize the client by setting the `profile` client option to `3.2`:

```php
$client = new Predis\Client($parameters, ['profile' => '3.2']);
```

Cheers!

**Comment by prashantidealittechno** [comment]
Hello nrk, When this feature will be available with package installation "predis/predis"
I run the command "composer require predis/predis" but it does not get version 1.0.4,
also I add like to composer Json and run composer update and it show message and it show error not version not found, can you please explain how can I use your updated code in my project or when new version will be available in on packgist with vesion 1.0.4?

**Comment by nrk** [comment]
@prashantidealittechno 1.0.4 is not out yet (when you are not sure you can [check here](https://github.com/nrk/predis/releases)) because the other day, just before releasing it, I found a bug in the handling of `redis-cluster` so I decided to wait a bit to confirm everything is fine after the fix. If I won't find anything broken I might tag the new release by tomorrow.

**Comment by prashantidealittechno** [comment]
@nrk OK thanks you so much.
