### ISSUE TITLE
Single element of array as Predis\Client constructor parameter

### ISSUE THREAD

**Issue by lulyon** [nrk/predis#348]
Intended to create a standalone client, however a cluster client created.

**Comment by nrk** [comment]
This is the intended behavior as [described here](https://github.com/nrk/predis#cluster), it doesn't matter if the array contains one or more elements.

**Comment by lulyon** [comment]
That is OK. How, to make my application code coherent, I'll  just keep the `Single element of array as Predis\Client constructor parameter to create a standalone client` patch in my own usage.

**Comment by nrk** [comment]
@lulyon it may look coherent from your own point of view but it's not coherent at all from the client's perspective: despite not being recommended at all, one could initialize the client to work with redis-sentinel or redis-cluster using just one node and the rest is done via autodiscovery. I'm not sure it's smart to move the logic needed to handle your own peculiar requirement to the internals of a library instead of adapting parameters before passing them to the client, especially considered it's just a one-liner, but that's up to you.

PS: using an indexed array without specifying either the `cluster`, `replication` or `aggregate` option will be [explicitly disallowed in v2.0](https://github.com/nrk/predis/blob/a4d63e25103413c08c63dac113b65d7393846d53/src/Client.php#L126-L142) to avoid confusion. The current behaviour is simply for to backward compatibility from back when Predis only supported clustering via client-side sharding.

**Comment by lulyon** [comment]
@nrk Thanks for your great explanation！Here I intend to initialize a client as standalone as long as `cluster, replication or aggregate option` is not set, which is an explicit rule in the context my application. However, thanks for pointing out the compatibility issue, I will  change my implementation a little bit to adapt that.
