### ISSUE TITLE
是否支持redis 3.2.1？

### ISSUE THREAD

**Issue by sn01615** [nrk/predis#353]
$config['redis_default']['host'] = 'localhost';		
$config['redis_default']['port'] = '6379';		
$config['redis_default']['password'] = '1234';		
$config['redis_default']['database'] = '0';

new Predis\Client($config['redis_default']);

new的时候浏览器返回：

{
status: -64000,
user_msg: "bad exception with msg: The underlying connection is not traversable",
fail_code: 0,
data: [ ],
time_begin: 1466993695.6252,
time_cost: 0.052510023117065,
trace: [ ],
ip: "0.187"
}

**Comment by nrk** [comment]
Please write in English, it might be hard for you but I don't understand Chinese. Futhermore, the next time please post the actual stacktrace of the exception instead of a blob of text generated by something I don't even know about.

The only place where an exception with the message is thrown is [`Predis\Client::getIterator()`](https://github.com/nrk/predis/blob/6ab10b2b705ea5121f2c1ea87a290f6871c32ebd/src/Client.php#L537-L539) and considering the parameters you passed to the client's constructor this means that you are trying to iterate over the client instance using `foreach` (for example `($client as $node) { }`) but you configured Predis to connect to a single Redis node. Iterating over the client is supported only when using aggregate connections such as clustering or replication.
