### ISSUE TITLE
set() fails when NULLs are passed to it

### ISSUE THREAD

**Issue by dannykopping** [nrk/predis#357]
According to the phpdoc of `ClientInterface`:

```php
* @method mixed  set($key, $value, $expireResolution = null, $expireTTL = null, $flag = null)
```

When executing `set("key", "value")`, this is the resulting command from `redis-cli monitor`:
`"SET" "key" "value"`

However, when `NULL`s are passed in for the TTL values:
`set("key", "value", NULL, NULL)` - they are passed along as-is to redis:

`"SET" "key" "value" "" ""`

...which leads to an exception.

**Comment by dannykopping** [comment]
Possibly some missing code, or a bad refactor?

https://github.com/nrk/predis/blob/v1.1/src/Command/Command.php#L31

`filterArguments` just returns the arguments without modifications

**Comment by nrk** [comment]
@dannykopping you are not supposed to pass NULL values to `SET` (or any other Redis command for that matter) since everything in Predis gets converted to string when passed as an argument to commands. Those NULLs in the phpdocs for Redis commands are just for the sake of documenting optional arguments as there's no other way to achieve that.
