### ISSUE TITLE
Using SCAN with Predis\Client

### ISSUE THREAD

**Issue by yahavb** [nrk/predis#364]
I need to run a full scan on the entire key sets. I could do it Redis client. Is there any way to scan all the map keys with Predis?

Thanks,

**Comment by nrk** [comment]
Hi @yahavb, you can use the very same [`SCAN`](http://redis.io/commands/scan) command like you'd do when using redis-cli or just leave the grim details of handling the iteration to Predis by using the [`Predis\Collection\Iterator\Keyspace`](https://github.com/nrk/predis/blob/v1.1.1/src/Collection/Iterator/Keyspace.php) iterator class so that you can simply use `foreach`, see [this example](https://github.com/nrk/predis/blob/v1.1.1/examples/redis_collections_iterators.php#L43-L47).

**Comment by yahavb** [comment]
Thanks so much that works!
