### ISSUE TITLE
Read request after write operation goes to master only

### ISSUE THREAD

**Issue by patelmanjeet** [nrk/predis#369]
We found any request after write goes to master always.

$parameters = ['tcp://ip-sentinel:26379' ];
$options  = ['replication' => 'sentinel', 'service' => 'resque'];

$client = new Predis\Client( $parameters, $options );

$value = $client->get('foo');  // goes to slave 
$client->set('foo', 'bar'); // goes to master 
$value = $client->get('foo'); // goes to master
$value = $client->get('foo'); // goes to master

Is any way to send read -> slave and  write -> master.

**Comment by cebe** [comment]
Do changes propagate to slaves immediately? If not I would consider this expected behavior, otherwise you might get the old value directly after write.

**Comment by patelmanjeet** [comment]
It's just added as sample code, we have different keys.

```
$value = $client->get('foo1');  // goes to slave 
$client->set('foo2', 'bar'); // goes to master 
$value = $client->get('foo3'); // goes to master
$value = $client->get('foo4'); // goes to master
```

Looking for setting which always send read to slave

**Comment by nrk** [comment]
@patelmanjeet that's the intended behaviour in order to avoid stale reads due to possible replication latencies (replication in Redis is asynchronous), but you can do `$client->getConnection()->switchToSlave()` after a write to ensure that the client switches back to using one of the slaves.

Alternatively you can create a client instance using the connection to the master server but that would defeat the automatic discovery-and-retry nature of the redis-sentinel backend:

```php
$masterConnection = $client->getConnection()->getMaster();
$masterClient = new Predis\Client($masterConnection, $client->getOptions);
```
