### ISSUE TITLE
Sentinel nodes auth bug...

### ISSUE THREAD

**Issue by Somebi** [nrk/predis#391]
```
// We explicitly set "database" and "password" to null,
            // so that no AUTH and SELECT command is send to the sentinels.
            $parameters['database'] = null;
            $parameters['password'] = null;
```

Why you have disabled password? How are we supposed to protect sentinel nodes without password? It is available to anyone without password...

requirepass is useless without this feature, vpn/tunneling is the only option without it.

Please return it back.

**Comment by nrk** [comment]
As far as I know there's no way to configure a password for sentinel nodes in the `sentinel.conf` and that's why the library does not send any `AUTH` command to **sentinel** instances. That said, `requirepass` is a configuration available in `redis.conf` which is used by the actual redis nodes and not by sentinel instances. When using sentinel-based replication, Redis servers **must share** the same password that's why when you create a new client instance you can set a common password (or a set of connection parameters) via client options as stated in the [`README`](https://github.com/nrk/predis#replication) file.

**Comment by Somebi** [comment]
Why no way? Just provide same password in config. They basically have the same AUTH feature. Try it yourself. It won't allow you to use any command until you provide proper AUTH command.

http://redis.io/topics/sentinel here is said:

**Sentinel** and Redis authentication

**Comment by Somebi** [comment]
Without it, anyone can easily connect to sentinel and issue any sentinel command...

**Comment by Somebi** [comment]
Btw other node sentinel modules like ioredis support this feature.

**Comment by nrk** [comment]
Quoted from that very same Redis documentation page about sentinel:

> When the master is configured to require a password from clients, as a security measure, slaves need to also be aware of this password in order to authenticate with the master and create the master-slave connection used for the asynchronous replication protocol.

It speaks about **master** and **slave** instances (and this is supported by Predis), not **sentinel** instances. The redis documentation is pretty clear about this, but you can also [read here](https://github.com/antirez/redis/issues/3279#issuecomment-230485169) where the author states clearly that sentinel nodes **do not support `AUTH`**.

**Comment by Somebi** [comment]
uh well... will have to make VPN after all... all these redis passwords became useless after all...
