### ISSUE TITLE
excuse me laravel redis  cluster configure

### ISSUE THREAD

**Issue by yb19890724** [nrk/predis#394]
excuse me laravel redis  cluster configure

**Comment by nrk** [comment]
I don't know what you meant to ask but this is not the place for asking Laravel-related questions even if they involve the use of Predis. You might want to start by heading to [more appropriate channels](https://laracasts.com/discuss/channels/laravel) to get support as the configuration of Predis may be different due to the wrapping of the client by the Laravel API.
