### ISSUE TITLE
php redis extension then phpiredis

### ISSUE THREAD

**Issue by mandevx** [nrk/predis#399]
Hi phpiredis as suggested does not support php7 and that is an issue for me , just wanted to ask of as in you readme suggested to use phpiredis can we use the other php redis extension https://github.com/phpredis/phpredis

**Comment by nrk** [comment]
phpiredis works perfectly fine with PHP 7.0, we even run [CI tests on this runtime](https://travis-ci.org/nrk/phpiredis/jobs/178652498) to ensure that. That said, it's impossible to make Predis use phpredis since this extension doesn't expose the needed bits (namely a parser/serializer of the protocol or a low-level way to queue raw commands and read their replies at a later stage).
