### ISSUE TITLE
Can`t call transaction command for sentinel replication

### ISSUE THREAD

**Issue by suren1986** [nrk/predis#404]
I'm using Laravel and going to deploy Redis Sentinel for HA. I can't make laravel queue work because PRedis is not support transaction for sentinel replication.

The test code is below:
```php
$client = new Client(
    [
        'tcp://192.168.0.11:26379',
        'tcp://192.168.0.12:26379',
        'tcp://192.168.0.13:26379',
    ],
    [
        'replication' => 'sentinel',
        'service' => 'default',
    ]
);

$client->transaction([], function($transaction) {
    $transaction->set('test', time());
});
```
It's report "Cannot initialize a MULTI/EXEC transaction over aggregate connections. "

I comment the throw exception code in predis/src/Transaction/MultiExec, it works fine and right.

Please help.

**Comment by nrk** [comment]
@suren1986 this is actually a limitation of the current design of Predis because the abstraction implemented in the library to handle transactions is based on the assumption that transactions don't work with aggregate connection objects such as the redis-sentinel connection backend. This is a very old design decision that kind of backfired years later, so I'm tryind to address this limitation in Predis 2.0 (it requires a few breaking changes).

That said, it's still possible to avoid `$client->transaction()`, which uses the above-mentioned abstraction, and just use the good old `MULTI` and `EXEC` commands (that is, `$client->multi()` and `$client->exec()`).

**Comment by suren1986** [comment]
@nrk Laravel use redis transaction in the function migrateExpiredJobs of Illuminate\Queue\RedisQueue, so I decide not to use Redis Sentinel in Laravel now and look forward to the 2.0 version PRedis.
Thanks for the reply and hard work!
