### ISSUE TITLE
EVAL on Redis cluster

### ISSUE THREAD

**Issue by tillkruss** [nrk/predis#405]
When using a Redis cluster we're seeing the following exceptions:

```
Predis\NotSupportedException: Cannot use 'EVAL' with redis-cluster.
Predis\NotSupportedException: Cannot use 'EVAL' over clusters of connections.
```

According to the [Redis docs](https://redis.io/commands/eval), this should be possible:

> All Redis commands must be analyzed before execution to determine which keys the command will operate on. In order for this to be true for EVAL, keys must be passed explicitly. This is useful in many ways, but especially to make sure Redis Cluster can forward your request to the appropriate cluster node.

Is there something we're doing wrong?

**Comment by nrk** [comment]
@tillkruss actually when using `EVAL` and `EVALSHA` with redis-cluster, Predis [makes sure that all of the keys passed to these commands](https://github.com/nrk/predis/blob/v1.1.1/src/Cluster/ClusterStrategy.php#L384-L402) are handled by the same hash slot before proceeding because (according to the [Redis docs](https://redis.io/topics/cluster-tutorial#redis-cluster-data-sharding)):

> Redis Cluster supports multiple key operations as long as all the keys involved into a single command execution (or whole transaction, or Lua script execution) all belong to the same hash slot. The user can force multiple keys to be part of the same hash slot by using a concept called hash tags.

I don't have a running cluster set-up at hand right now to verify if this behaviour still holds true or it actually changed in further iterations of redis-cluster, but it might be useful to double check this just to make sure.

**Comment by tillkruss** [comment]
@nrk: My mistake, I didn't use `{...}` hash tags. Works flawless.
