### ISSUE TITLE
Timeout causing all php request to fail 

### ISSUE THREAD

**Issue by mpoiriert** [nrk/predis#409]
I am getting this error

Uncaught PHP Exception Predis\Connection\ConnectionException: "Connection timed out [XXX]" at ./vendor/predis/predis/src/Connection/AbstractConnection.php line 168

I am using Predis trough symfony/SncRedisBundle and AWS.

The issue we see is that once we get a connection timed out almost all the other request on the same server fail. We need to start a new EC2 machine. We don't see any other weird behaviour. Right now we have only 1 php server and a 1 master / 1 replication elasticache setup. Before Christmas we had about 30 servers and it happen to almost half of them at the same time. Look like a issue on the infra is triggering the problem but we are wondering why all subsequent request are still failing but a new php server will be able to work properly.

I have open the same issue on phpredis

https://github.com/phpredis/phpredis/issues/1089

**Comment by nrk** [comment]
Try doing a `netstat -antp | grep php | awk '{print $6}' | sort | uniq -c | sort -n` on one of the EC2 instances where php-fpm is running to see how many connections are established by php-fpm, you can also add another `grep ":6389"` or the TCP port redis-server is bound to in order to count only the connection to Redis if your php processes are connected to other services. Did you also try to restart the php-fpm process instead of launching a whole new EC2 instance? There could also be an ephemeral port exhaustion issue on the instance running the redis server, but in all honesty I don't know how ElastiCache works.

**Comment by mpoiriert** [comment]
Thanks for the info, next time it's happening will try this on one of the instance so we could have more data to investigate. I'll put the info here once we have it and/or the solution if we find it.

**Comment by nrk** [comment]
Closing due to lack of further feedback, but feel free to post more details if needed.

**Comment by itbdw** [comment]
@mpoiriert 
Do you still get this error now? I just resolve this problem by setting the redis server `timeout` to a none zero value. What I found is my redis server hold some long time idle connections, when the client try to new connection, error comes out. So after I set the `timeout`, redis serve kill the outdated connection, and here comes peace. Hope helps :)

**Comment by mpoiriert** [comment]
Thanks for the info ! Not working for the company that had this problem. I
did forward the info to the technical contact over there.
