### ISSUE TITLE
ERR unknown command 'HSCAN'

### ISSUE THREAD

**Issue by ismail0234** [nrk/predis#412]
PHP version : 7.0
Redis version : 3.1

Fatal error: Uncaught Predis\Response\ServerException: ERR unknown command 'HSCAN' in

why hscan command error ?

**Comment by nrk** [comment]
A `Predis\Response\ServerException` exception means that the error is returned by Redis itself, meaning that you are actually connecting to a Redis server older than 2.8.0 if Redis is reporting that [`HSCAN`](https://redis.io/commands/hscan) is an unknown command. Please verify your setup.

**Comment by ismail0234** [comment]
php redis version 3.1.0 ,but Fatal error: Uncaught Predis\Response\ServerException: ERR unknown command 'HSCAN' in

**Comment by nrk** [comment]
The fact is that it's simply not possible that it's an issue with Predis, you either are connecting to a wrong Redis server or HSCAN [was somehow disabled](https://redis.io/topics/security#disabling-of-specific-commands). Check the output of `$client->info()` instead of assuming that the version of Redis you have installed is the actual one you are connecting to, it wouldn't be the first time that someone opened an issue when they were simply connected to a wrong server for whatever reason.

**Comment by ismail0234** [comment]
yes php version 3.1.0
but, predis version 2.4.6

![sadsdasadsadsadsad](https://cloud.githubusercontent.com/assets/20711301/22431313/c6eabd52-e719-11e6-9680-cddfa3d9ccb3.png)

**Comment by nrk** [comment]
1. You even highlighted the output of `INFO` with a red box: `[redis_version] => 2.4.6`.
2. You are not even using Predis as the output of `phpinfo()` indicates that you are using [phpredis](https://github.com/phpredis/phpredis).

**Comment by ismail0234** [comment]
I am use Predis library.

![dddd](https://cloud.githubusercontent.com/assets/20711301/22437088/4e759e3a-e72f-11e6-8ced-529a5a4e3d21.png)

**Comment by nrk** [comment]
The _Redis_ section in `phpinfo()` doesn't mean that you have Redis 3.1.0 running but that you have the _phpredis_ extension version 3.1.0 configured in PHP, this is shown even if you are not actually using it. **The `redis_version` field returned in the response to `$client->info()` indicates the Redis version you are connected to**, which in this case is 2.4.6 and is older than 2.8.0 when `HSCAN` was introduced. Hope everything is clear now.
