### ISSUE TITLE
File not getting included when using bin/create-single-file

### ISSUE THREAD

**Issue by abhishekbuyt** [nrk/predis#413]
trying to compile predis into hhvm, so wanted to use the tool to make a single includable file.
2 main issues till now. 
1) HipHop Parse Error: Cannot mix bracketed namespace declarations with unbracketed namespace declarations --- fixed it by manually transforming the namespace declaration 
after that ----
2)Fatal error: Class undefined: Predis\Configuration\ConnectionFactoryOption
it seems the single file generated did not include this Class.

Am i missing something. Please advise how to use the create-single-file

**Comment by nrk** [comment]
Actually I've never tested [`create-single-file`](https://github.com/nrk/predis/blob/v1.1.0/bin/create-single-file) with HHVM mostly because that script is old stuff (and frankly quite hackish too) and it doesn't even make much sense to have these days. I will see if I can quickly find a fix but I cannot guarantee anything as I have other priorities for Predis right now and [`create-single-file`](https://github.com/nrk/predis/blob/v1.1.0/bin/create-single-file) will most likely be removed anyway in a future major release.

**Comment by abhishekbuyt** [comment]
Thanks for the response. Any suggestion on how to get the best performance in HHVM would help. Thanks.

**Comment by nrk** [comment]
Maybe I'm missing something here but php files are parsed and compiled into the HHVM bytecode by HHVM itself on the first request (more or less, I'm not considering further JIT optimizations here). Having one big PHP files doesn't really have any benefit anyway, actually it will just consume more memory by caching classes that in most cases won't even get used.

**Comment by abhishekbuyt** [comment]
Actually i was trying to put predis into the hphp/system/php and have it compile with hhvm as an extension. was successfully able to do it after tinkering it. now getting a different error when i try to make a redis-cluster connection with it.

Catchable fatal error: Argument 1 passed to Predis\Connection\Aggregate\RedisCluster::__construct() must be an instance of Predis\Connection\Aggregate\FactoryInterface, Predis\Connection\Factory given

Assuming that this process will have some performance benefit. 
Note: predis inclusion at run time with autoloader works perfectly.

**Comment by nrk** [comment]
Oh I see, didn't actually undestand that you were trying to compile it as an extension. `FactoryInterface` is in the in the `Predis\Connection` namespace and not in the `Predis\Connection\Aggregate\` namespace, it's either `create-single-file` that generated something bogus or it's HHVM having issues when trying to compile Predis as an extension. After all that class is [correctly aliased in `Predis\Connection\Aggregate\RedisCluster`](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/RedisCluster.php#L20)

**Comment by abhishekbuyt** [comment]
Fount it. Was another error introduced bu the create-single-file. 
wrong class type in the constructor of **class RedisCluster implements ClusterInterface**

now works properly after recompile. Thanks.

Will run performance some tests and update on the performance boot if any ...

**Comment by nrk** [comment]
Nice, I'm actually curious to know if you'll notice any difference in performances 🙂

**Comment by abhishekbuyt** [comment]
Test a few rounds . No noticeable difference in performance. :( ..
If you can point me to the core class responsible for the performance difference in php-redis and predis, may be i will try to write that part in native cpp , get rid of the performance gap in HHVM.

**Comment by nrk** [comment]
I don't think there's a single class that accounts for the difference between Predis and the Redis client shipped with HHVM, Predis is more complex after all, but [Predis\Connection\StreamConnection](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/StreamConnection.php) is probably the lowest-level class that have an impact for sure since it handles both the network-level communication and parses / serializes the Redis RESP protocol.

**Comment by abhishekbuyt** [comment]
Okay, Will see what i can do about porting it for HHVM. Leaving for my own wedding today :)
Catch you in a couple of weeks

** this would be my first contribution to opensource. Be Gentle :)

**Comment by nrk** [comment]
Hey congrats for the wedding! :tada: :smile:

**Comment by abhishekbuyt** [comment]
Thanks :)

**Comment by nrk** [comment]
I'm closing this issue since [`create-single-file`](https://github.com/nrk/predis/blob/v1.1.0/bin/create-single-file) will most likely be removed in Predis v2.0 anyway, and support for HHVM for the next major release won't be a top priority anymore.
