### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by Nerfair** [nrk/predis#415]
Code bellow ads about 60ms to code execution time on vagrant, and when you have 3 SQL selects with some formatting in PHP, and their total time is about 2-3 ms, adding 60 more is huge lag.

            $redis = new \Predis\Client;
            foreach(range(1, 1000) as $i) {
                $redis->time();
            }

Instead of `time()` can be `get()` or `hget()` but result is same, it's looks like the reason of lag is "initiating" of redis, or connection establishment or something like this, not the query, but problem still exists, executions is slow. 

Question is, is it okay and i must find a workaround?

**Update**

Looks like it's my redis server, not predis client problem

    redis-benchmark -c 1 -n 1000

returns `1000 requests completed in 0.10 seconds` almost for all types of query

**Comment by nrk** [comment]
It definitely doesn't seem OK for 1000 requests if the client is connected to a Redis instance on the localhost, but it may be somehow normal, at least to a certain degree, if the Redis instance is running on a different host due to network round-trip timings when the client sends a request and waits for the response (see the [last part of our FAQ](https://github.com/nrk/predis/blob/v1.1.1/FAQ.md#predis-is-a-pure-php-implementation-it-can-not-be-fast-enough)). Pipelining commands helps in most cases. This isn't really a bug or a client issue anyway, so I'm closing it but feel free to post more details if needed.
