### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by jorge07** [nrk/predis#423]
I noticed that the repo has less activity than I expected and I intensively working with this lib at work. Are you looking for help or maintainers?

Thanks in advance

**Comment by nrk** [comment]
Hello @jorge07, I'm certainly busy but I'm not actively looking for help or maintainers.... contributions are still appreciated as usual!

The code in the v1.x branch is actually quite stable and Redis hasn't seen any big new feature introduced in months, that's the main reason why there's not much activity in the repository and less activity doesn't necessarily translate to an abandoned project. As for v2.x (the current `master` branch), as usual I'm taking things very slow since I don't want to step on the gas when I'm not sure about some changes and I don't want to regret a few decisions later when a stable release is out in the wild.

**Comment by jorge07** [comment]
Hi @nrk, ok! I saw some lack of activity when I opened a pr but I understand. Thanks
