### ISSUE TITLE
Can return response from subscribe? 

### ISSUE THREAD

**Issue by rustem-art** [nrk/predis#449]
Hi! Thank you for best lib!

I use predis and i want subscribe to channel in PHP and wait 30 seconds. If not receive any messages at channel, return json response. Or if messages in channel exists, return response too and exit

.For example i want, that my Redis::subscribe return $message and i can return response. I have a some code in Controller in Laravel: 

```
Redis::subscribe(['PushAuthChanel'], function($message) {
echo $message; // Nothing happens
return response()->json($c, 200); // Nothing happens
//return $message; // Nothing happens too
});
```

And why Redis::subscribe can not return $message? But it well return exit code like this:

```
Redis::subscribe(['PushAuthChanel'], function($message) {
return exit(0); //will work
dd($message); //will work fine
});
```

Thank!

**Comment by nrk** [comment]
This seems more of a question related to Laravel, I don't even know what the static method `Redis::subscribe` does since it's not from Predis so I guess you should ask on some Laravel-related forum.

That said, in Predis any return value from callbacks used for PUB/SUB is simply ignored because it doesn't even make sense to be considered anyway (the same callback can be invoked multiple times, that's the whole point of PUB/SUB after all, so which value would you return?). It's not even possible to set a timeout when using Redis PUB/SUB, maybe you should just use a command like [`BLPOP`](https://redis.io/commands/blpop) but again, this is not really related to Predis.

**Comment by rustem-art** [comment]
@nrk Ok, thank you for answer ;)
