### ISSUE TITLE
Client::set() method with null variables error

### ISSUE THREAD

**Issue by knyk** [nrk/predis#452]
` * @method mixed  set($key, $value, $expireResolution = null, $expireTTL = null, $flag = null)`

according to `ClientInterface` that method has default nulls in last 3 arguments.
It is possible to call `Client::set('key', 'value')`, `Client::set('key', 'value', 'ex', 5)`
but when trying to call `Client::set('key', 'value', null, null, null)` it throws an error 
```
Predis\Response\ServerException: ERR syntax error

/var/www/html/vendor/predis/predis/src/Client.php:370
/var/www/html/vendor/predis/predis/src/Client.php:335
/var/www/html/vendor/predis/predis/src/Client.php:314
/var/www/html/app/Service/RedisService.php:60
```

redis version 3.2.9, predis version 1.1.1

**Comment by nrk** [comment]
@knyk actually that's only a way to describe these parameters as optional since there's no way to explicitly mark them as such with phpdoc AFAIK. If you explicitly set their value to `NULL`, Predis will convert that value to an empty string that will be passes as such (that is, as an empty parameter but still present in the actuall command payoload) to Redis.
