### ISSUE TITLE
Re-execution of the command in case of error

### ISSUE THREAD

**Issue by howkey666** [nrk/predis#454]
Hi,
sometimes happen that command fails because of error like **Error while writing bytes to the server**. And a lot of these errors can be handled just by re-execution of them. So I am trying to write a wrapper. Currently, it is very simple:

`
class Client extends \Predis\Client
{

    /**
     * @inheritdoc
     */
    public function __call($commandID, $arguments)
    {
        try {
            return parent::__call($commandID, $arguments);
        } catch (\Predis\Connection\ConnectionException $e) {
            if (strpos($e->getMessage(), 'Error while reading line from the server') === false
                && strpos($e->getMessage(), 'Error while writing bytes to the server') === false) {
                throw $e;
            }

            $this->disconnect();
            $this->connect();

            return parent::__call($commandID, $arguments);
        }
    }

}
`

But I am not sure if it's safe to re-execute command in case of error **Error while writing bytes to the server** 
It can happen when there is a problem with writing to socket:
https://github.com/nrk/predis/blob/v1.1/src/Connection/PhpiredisSocketConnection.php#L355

Imagine the situation when you are sending command `LPUSH key value value value`. You write it to socket and `socket_write()` will return that only `LPUSH key value` was written. Then you will try to send rest of the data and receive the error. Will the command be executed partially?

Maybe this option, to send command which will be automatically re-executed in a case of some errors, could be part of the predis. What do you think?

**Comment by nrk** [comment]
Variadic commands like `LPUSH` are executed atomically by Redis only once the whole command payload has been received by the server, so in case of a network timeout or any kind of error during the write operation on the socket will end up in the command not being executed at all.

As for an automatic retry mechanism, implementing something useful for everyone (different requirements) would be hard and make the complexity of the implementation skyrocket, that's why Predis does not support anything like that.
