### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by 0x13a** [nrk/predis#484]
* Is there any API documentation?
* If so, can I contribute in some way?

**Comment by nrk** [comment]
@0x13a unfortunately Predis is lacking when it comes to API documentation, I'm perfectly aware of this but I can't help it since I don't have enough time to work on something aside the actual code (and since I suck at writing good docs anyway, it would most likely require even more time than needed if I did that alone). 

My dream would be having a basic set of docs for common use cases and a more detailed set of docs illustrating the internals of the library. A few months ago I discovered [this repository](https://github.com/ProgerXP/predis-doc) which has an accurate description with a few examples here and there of how Predis internally works (so it's not just the public API of `Predis\Client`) and I think it'd be a great starting point for an extensive and useful set of docs for the library, so much so that when I had a brief email exchange with @ProgerXP, which authored everything in that repository, I agreed with him about the idea of making it the official documentation for Predis beginning with just a few minor fixes and changes. As usual, the greatest and most immediate issue is the time to make this happen :disappointed: but I'm still positive about the idea.

**Comment by ProgerXP** [comment]
@nrk, thanks for confirming again that my documentation may eventually become Predis' official docs. I might gather enough free time in the upcoming months to make the required changes (mainly cleanup and example checks). If this happens, I'll post back in this issue.
