### ISSUE TITLE
read_write_timeout not working in predis with cluster and persistent connections

### ISSUE THREAD

**Issue by sreeraagbuyt** [nrk/predis#490]
```
$client = new \Predis\Client([
        'tcp://192.168.24.128:8001?slots=0-5460&persistent=1&timeout=0.05&read_write_timeout=0.05',
        'tcp://192.168.24.128:8002?slots=5461-10922&persistent=1&timeout=0.05&read_write_timeout=0.05',
        'tcp://192.168.24.128:8003?slots=10923-16383&persistent=1&timeout=0.05&read_write_timeout=0.05',

    ], ['cluster' => 'redis'
    ]);

$start = microtime(true)
$client->rpush( "oxReqQueue", "bla bla bla");
print_r(microtime(true) - $start) // gives me value in order of 200 to 500 milliseconds.

```
We have set a timeout of 50 milliseconds but calls take > 50 milliseconds. Checked this from timing calls using grafana and also using above code. 
But if I set that value to something like 0.5 milliseconds, then all calls are timing out.
Can someone please help me with this?

**Comment by nrk** [comment]
First of all it's advisable to use _default connection parameters_ when you need a few common parameters applied to all the connections in the pool of redis-cluster, that's because these parameters are applied even to new connection discovered at runtime by the client when new nodes of the cluster that were not part of the initial pool specified by the explicit configuration are returned by Redis. Default connection parameters can be passed when initializing the client with the `parameters` client option, for example:

```php
$client = new Predis\Client($clusterNodes, [
    'cluster' => 'redis',
    'parameters' => [
      'timeout' => 0.05,
      'read_write_timeout' => 0.05,
    ],
]);
```

That said I've never noticed this kind of issue, the difference between 50ms and 200ms is quite large. Timeouts on network streams are handled by PHP internally so once you specify a timeout it's kind of transparent to Predis.

What happens if you try with a second identical command and a third slightly different command (just enough to have it land on a different node) and then measure the timings for that call?

**Comment by nrk** [comment]
I'm closing this due to lack of feedback, feel free to re-open it if you have more details to share and are still interested in it.

**Comment by edslourenco** [comment]
Hi @nrk, I'm trying to send the parameters as you said, but they don't work. They only work by sending with hosts

Working:
```php
$client = new \Predis\Client(
    [
        'tcp://aaa?timeout=0.05&password=x',
        'tcp://bbb?timeout=0.05&password=x',
        'tcp://ccc?timeout=0.05&password=x',
    ],
    [
    	'cluster' => 'redis'
    ]
);
```

Not working:
```php
$client = new Predis\Client(
    [
        'tcp://aaa',
        'tcp://bbb',
        'tcp://ccc',
    ], 
    [
    	'cluster' => 'redis',
    	'parameters' => [
    	    'password' => x,
      	    'timeout' => 0.05,
      	    'read_write_timeout' => 0.05,
    	],
    ]
);
```

Should it work both ways?
