### ISSUE TITLE
Connection refused [tcp://redis:tcp://172.17.0.2:6379]

### ISSUE THREAD

**Issue by ghost** [nrk/predis#495]
I just created, solved, and recreated this, I wouldn't necessarily call it a bug but wanted it to be here if others run into this problem.  This is specific to docker containers as far as I can tell.

I have multiple docker containers, php, nginx, mysql, redis.  All named that because I hate naming things.  Inside the docker-compose, I have links: - redis to link laravel to my redis container for event broadcasting.  Node can attach to redis fine with this name, but it's super simple.

When the event fires, this error comes up, however this is what laravel/predis thinks the address is for the redis server.
Connection refused [tcp://redis:tcp://172.17.0.2:6379]

Looking at the code in StreamConnection.php line 156, it concatenates the $parameters->host and $parameters->port, but I can't figure out why the port has already been concatenated.

```
Predis\Connection\Parameters {#935
  -parameters: array:5 [
    "host" => "redis"
    "password" => null
    "port" => "tcp://172.17.0.2:6379"
    "database" => 3
    "scheme" => "tcp"
  ]
}
```
I suspect because the host name/link name is just 'redis' which matches throughout laravel, that it gets confused.  If I rename the redis container to something arbitrary, redis-server-db and setup links that way, the problem goes away.  

Really, just signifying that the words redis and maybe redis-server are reserved words would be sufficient, I don't think a code fix is necessary or that this is a code bug, but it's definitely something you can get yourself into. This can be closed if you like, just felt like it should be put out there.

**Comment by nrk** [comment]
Maybe you should file this in the Laravel issue tracker since Predis doesn't mangle in any way the value of `port` passed by the user to the client constructor. What should be the exact URI string / parameters array pointing to your redis server running in the docker instance?

**Comment by j88per** [comment]
Yeah I wasn't sure and still haven't figured out where the malforming occurs, I can't find where $paramters are set yet.  Expected is just as the code performs concatenating, tcp://172.17.0.2:6379.  Which works great when the name is changed.

**Comment by cyrossignol** [comment]
@j88per When you use linked containers (_deprecated!_), Docker [sets environment variables in the container](https://docs.docker.com/compose/link-env-deprecated/) to make it easier to discover the linked services. 

In this case, because the link name is `redis`, Docker sets the `REDIS_PORT` environment variable to the full URL of the linked service (_tcp://172.17.0.2:6379_). This is the same variable that Laravel consumes for its Redis configuration, so the framework reads it into the config. This occurs even when we specify the variable in the _.env_ file because the phpdotenv library doesn't overwrite variables that already exist in the environment.

Instead of using container links, consider switching to [proper Docker networking](https://docs.docker.com/compose/networking/). Compose sets up a default network for us and resolves hostnames between containers according to a container's service name, so the link isn't needed in the first place.

**Comment by guoxiangke** [comment]
https://github.com/laravel/framework/issues/7904
