### ISSUE TITLE
client->isConnected() return false when in cluster mode

### ISSUE THREAD

**Issue by dragon753** [nrk/predis#498]
I am sure the connection is ok.

**Comment by chishiuanlu** [comment]
Having same issue. Need more support and documentation for Cluster mode...

**Comment by nrk** [comment]
`Predis\Client::isConnected()` returns `true` if the client opened a connection to [at least to one of the nodes](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/RedisCluster.php#L83-L95) during the lifecycle of the script. I'm closing this issue because I couldn't reproduce it, but feel free to re-open it if you can provide more details (like a trace generated by xdebug which are useful to investigate what's going on when that happens) and obviously if you are still interested in this.
