### ISSUE TITLE
[documentation] arbitrary binary getting/setting?

### ISSUE THREAD

**Issue by dkrieger** [nrk/predis#502]
# Background

For performance reasons, I'd like to store integer keys/values in redis as raw binary. On a typical modern system (64bit), php stores integers as 64bit (8 byte) signed integers. The numbers I want to store in redis only require 3-4 bytes, and doubling that footprint is not acceptable in my use case. It isn't really documented how to accomplish this with Predis. My assumption is that [pack][1] and [unpack][2] would need to be used by the calling code, at least if we want to avoid the space inefficiency (and we do) introduced by the path of least resistance, base64 encoding/decoding.

[1]: https://secure.php.net/manual/en/function.pack.php
[2]: https://secure.php.net/manual/en/function.unpack.php

# Documentation

If you could enlighten me on whether/how Predis can handle this usage, I'd be happy to submit a PR to address this in the documentation. If this is already addressed somewhere I missed, I apologize for raising the non-issue.

**Comment by nrk** [comment]
@dkrieger it could be indeed handled using _pack()_ + _unpack()_ since Predis simply passes the payload as raw binary data (and Redis stores everything as such), but I guess that would be standard practice in a case like yours and not really related to Predis (as a client) or Redis (as a key-value store).
