### ISSUE TITLE
Question: Sentinel and Session handler

### ISSUE THREAD

**Issue by kornrunner** [nrk/predis#503]
Given three redis servers, where one is master and two are slaves, and every server having a sentinel instance overlooking the setup, and given that `phpiredis` extension is installed - would the following code be alright?

```php
<?php

use Predis\Client;
use Predis\Session\Handler;

$options = [
    'prefix' => 'session:',
    'replication' => 'sentinel',
    'service' => 'sessions',
    'connections' => [
        'tcp'  => 'Predis\Connection\PhpiredisStreamConnection',
        'unix' => 'Predis\Connection\PhpiredisSocketConnection',
    ],
];

$sentinels = [
    'tcp://192.168.0.1:26379',
    'tcp://192.168.0.2:26379',
    'tcp://192.168.0.3:26379',
];

$client  = new Client($sentinels, $options);
$handler = new Handler($client, ['gc_maxlifetime' => ini_get('session.gc_maxlifetime')]);
$handler->register();
```

Thank you!

**Comment by nrk** [comment]
Hi @kornrunner, it should be fine. Do you have any issue with that?

**Comment by kornrunner** [comment]
It works until it doesn't ... it sometimes prematurely ends / drops sessions. IPs are correct, sentinels are responding, sentinel group name is alright, I'm not seeing anything odd in logs - but will keep looking around and let you know if I find anything.

Thank you!

**Comment by nrk** [comment]
@kornrunner one thing you could try is adding `$client->getConnection()->switchToMaster()` after initializing the client, and see if anything changes. This will force the client to stick with the master server even when read-only commands are issued (e.g. `GET` being [used here](https://github.com/nrk/predis/blob/v1.1.1/src/Session/Handler.php#L95-L102)) which normally, as the default behaviour of Predis, are sent to slaves in order to offload the main server instance. Please note that the auto-discovery proces will be fired immediatly which means that connection to sentinel(s) won't be lazy anymore, but it could be worth a try for a quick test.

When a new session is created, the related key/data pair is stored on the master server and slaves receive that data asynchronously via replication. I suspect that when a query for session data happens immediatly after the very same session ID was created by a separate script, the data may not be found on slaves yet. To be honest I've never really stored PHP sessions on Redis when using replication (sentinel-backed or not) so this is just a gut feeling :smile:

**Comment by kornrunner** [comment]
I'm usually deploying session handler with redis cluster and I hand no issues there. This setup with sentinel is applied because I needed HA, and there won't be a large amount of sessions - so cluster isn't required.

Switching/forcing sentinel connection to use master helped in my case, thank you!

**Comment by nrk** [comment]
> Switching/forcing sentinel connection to use master helped in my case, thank you!

Glad it helped. This reminds me I should make it configurable using options, as this would help keeping sentinel connections lazy.
