### ISSUE TITLE
app crashes if connection is not found.

### ISSUE THREAD

**Issue by jay754** [nrk/predis#515]
Hi,

Is it possible to override a redis connection failure? The app that we have crashes if redis connection is not found. We tried overriding the redis connection, but it won't work.

Thanks

**Comment by nrk** [comment]
Hi @jay754, if you need to make sure that the connection to Redis is available and does not break your application if the server cannot be reached then you should explicitly do a `$client->connect()` instead of relying on the lazy behaviour of Predis, and catch the exception. See #223 for an example, and the paragraph of the README that recites: 

> Connections to Redis are lazy meaning that the client connects to a server only if and when needed. While it is recommended to let the client do its own stuff under the hood, there may be times when it is still desired to have control of when the connection is opened or closed: this can easily be achieved by invoking $client->connect() and $client->disconnect().

**Comment by jay754** [comment]
Thanks @nrk
