### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by jondmcelroy** [nrk/predis#524]
No new merges/commits into master since middle of 2017 and @nrk does not appear to have regularly worked on it since 2016.

**Comment by jayesbe** [comment]
I have been using this package as well for last couple of years but it seems time to migrate to [phpredis](https://github.com/phpredis/phpredis) which seems to be more actively maintained.

**Comment by nocive** [comment]
Although phpredis is a native C extension, I can tell you from experience you'll run into all sorts of issues with TTLs and all sorts of inconsistent behaviour depending on your server version and the php extension version.  It's extremely unreliable and buggy, sadly.

I'm actually in the process of switching an entire codebase to use predis instead of phpredis precisely because of this.

**Comment by jondmcelroy** [comment]
Well at this point the answer is clear that this project is not currently maintained. No merges since 2017 and no real active work since 2016. No response from @nrk.

Does anyone have a suggestion for a fork that we can move all of the issues or PRs to?

**Comment by tillkruss** [comment]
I'll be taking over the development of Predis.
