### ISSUE TITLE
Persistent connections?

### ISSUE THREAD

**Issue by roelmonnens** [nrk/predis#530]
Could you explain when persistent connections should work and when they don't?
In my research about this I'm finding lots of contradictions about this subject.

In my own use case I can't get it to work. 
I'm using aggregated connections to 3 or more redis machines. My PHP code runs with nginx/php-fpm (all latests versions).

**Comment by nrk** [comment]
First of all when you are using aggregate connections you should set a different string value (instead of a boolean) for the `persistent` option of each set of connection parameters. You can read on #139 why this is neeed and the commit message of 8277afc for details on how it is intended to work with the current stable version of Predis.

For example:

```php
$redis01 = 'tcp://10.10.10.1:6379?persistent=redis01';
$redis02 = 'tcp://10.10.10.2:6379?persistent=redis02';
$redis03 = 'tcp://10.10.10.3:6379?persistent=redis03';
```

This will create three different persistent connections instead of erroneously reusing the first one.

PHP processes will keep these stream resources open at the end of the lifecycle of a script and they will be reused when a new client instance is created with parameters having the same host + port + value specified in `persistent`. Please note that a stream resource (thus its persistence state) is limited to the single PHP process which means that when using PHP-FPM, which coordinates and reuses multiple child processes under the hood, you will actually see more connections being created anyway (as many as child PHP processes up and running, at least).
