### ISSUE TITLE
Support for KEYS* command with redis clustering in laravel 4.2

### ISSUE THREAD

**Issue by shamsh0737** [nrk/predis#575]
i am not able to find all matching key in laravel 4.2 version. if i use redis cluster on server.

**Comment by nrk** [comment]
Aside from Predis not being related to Laravel, it's not possible to rely on `KEYS` when using redis-cluster, this is not a bug or missing feature but it's simply a limitation due to how clustering works.

The best workaround to replicate such a feature is to send a `KEYS *` command (which is generally discouraged anyway, at least in production) to each node of the cluster and then merge results into one single array. Obviously this won't be atomic in any way, and will most likely end up being slow depending on the population of your keyspace.

This is a crude example of how you can obtain this by iterating against a client instance configured to use redis-cluster:

```php
$keyspace = [];

foreach ($client as $clusterNode) {
    $keyspace = array_merge($keyspace, $clusterNode->keys("*"));
}
```
