### ISSUE TITLE
Predis on docker warning: Uncaught Predis\NotSupportedException: Cannot use 'PING' over clusters of connections.

### ISSUE THREAD

**Issue by SAGOlab** [nrk/predis#590]
Hi there,

I have 3 container on docker, the first for my php application, the second for redis, the third for nginx.

when I try to ping redis from my php container through a php file, it return me this warning:

> *Uncaught Predis\NotSupportedException: Cannot use 'PING' over clusters of connections.*

this is my php script:

```
$this->redis_conn = false;

$basepath = $_SERVER['DOCUMENT_ROOT'];
require ($basepath . $this->vendor_dir . self::PREDIS) . 'src/Autoloader.php';
Predis\Autoloader::register();

try {
        $options = array();
        $this->redis_conn = new Predis\Client(array($this->database_scheme, $this->database_host, $this->database_port, $options));
        $ping_conn = $this->redis_conn;

        echo $ping_conn->ping();

} catch (Predis\Connection\ConnectionException $e) {
         trigger_error("Database connection failed: " . $e->getMessage(), E_USER_WARNING);
         return false;
}

return $this->redis_conn;
```

There is a way to solve this issue and to check the redis connection?

thanks all.

**Comment by nrk** [comment]
Hi @SAGOlab,

You are configuring the client instance in a wrong way.

If you pass an indexed array instead of a named array (with keys being the connection parameters fields) then the client thinks that you are passing an array of nodes for a cluster of Redis servers which is not what you want here. Also, `PING` is not allowed when in cluster mode and that's why you get that error.

The proper configuration for connecting to a single Redis instance is [described in the README](https://github.com/nrk/predis#connecting-to-redis) file. Essentially, to mimick your snippet, the client instance should be created like this:

```php
$client = new Predis\Client([
    'scheme' => $this->database_scheme,
    'host'   => $this->database_host,
    'port'   => $this->database_port,
]);
```

Also do not use `Predis\Client::ping()`, it adds some useless overhead as it actually sends a command and reads a response back. Just use `Predis\Client::ping()`, it's enough for what you are trying to do.
